# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BjCli < Formula
  desc "A simple CLI blackjack game written in Go"
  homepage "https://github.com/arlomcwalter/bj-cli"
  version "1.0.1"

  on_macos do
    url "https://github.com/arlomcwalter/bj-cli/releases/download/v1.0.1/bj-cli_1.0.1_darwin_all.tar.gz"
    sha256 "22a01ea6b4e3921311222e916a4ea16e0c3f9a02cf3b0704fc0c71771453eac4"

    def install
      bin.install "bj-cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/arlomcwalter/bj-cli/releases/download/v1.0.1/bj-cli_1.0.1_linux_amd64.tar.gz"
      sha256 "6faaf1be3ae005c0debc015dcba40e10792bf9dbf2f37fb5587dd5c49c08d640"

      def install
        bin.install "blackjack"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arlomcwalter/bj-cli/releases/download/v1.0.1/bj-cli_1.0.1_linux_arm64.tar.gz"
      sha256 "e7d107c761fc38a599fca4c581fa8e77f9eb22f12af0fa191d5fdfb6e37e571b"

      def install
        bin.install "blackjack"
      end
    end
  end
end
