# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BjCli < Formula
  desc "A simple CLI blackjack game written in Go"
  homepage "https://github.com/arlomcwalter/bj-cli"
  version "1.0.3"

  on_macos do
    url "https://github.com/arlomcwalter/bj-cli/releases/download/v1.0.3/bj-cli_1.0.3_darwin_all.tar.gz"
    sha256 "9990462d131db41655d3df6fb75cdc7761b183c099c81f184a197561e0f008d0"

    def install
      bin.install "bj-cli"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arlomcwalter/bj-cli/releases/download/v1.0.3/bj-cli_1.0.3_linux_arm64.tar.gz"
      sha256 "a1800e3fa8a66e2b4cb83b6e5e368d405b94119e39e9b0825cbec04b974f5981"

      def install
        bin.install "blackjack"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/arlomcwalter/bj-cli/releases/download/v1.0.3/bj-cli_1.0.3_linux_amd64.tar.gz"
      sha256 "651ccd68d9fc8cb36b392ceeb647f352d88a19874c19ac739832e7e72d30ae0c"

      def install
        bin.install "blackjack"
      end
    end
  end
end
