# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pylai < Formula
  desc "Simple cli totp manager and authenticator"
  homepage "https://github.com/arlomcwalter/pylai"
  version "1.0.0"

  on_macos do
    url "https://github.com/arlomcwalter/pylai/releases/download/v1.0.0/pylai_1.0.0_darwin_all.tar.gz"
    sha256 "cd8fd80ac73ac5f8dec737eae148cc2f9e1b7bbac5c3403c24c80bf9ad6dfdd8"

    def install
      bin.install "pylai"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arlomcwalter/pylai/releases/download/v1.0.0/pylai_1.0.0_linux_arm64.tar.gz"
      sha256 "320240f082250ed594932f5006152d7460258a547fcf11f838f7d9abc40d392d"

      def install
        bin.install "pylai"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/arlomcwalter/pylai/releases/download/v1.0.0/pylai_1.0.0_linux_amd64.tar.gz"
      sha256 "77a1aec40cb8e89b4c86f9b50e216acc86981b4ac3d35ed31155f036534b5597"

      def install
        bin.install "pylai"
      end
    end
  end
end
